version: '3.7'
services:
  LearningWebsite-Docker:
    environment:
      - CONTEXT_PATH=/LearningWebsite
      - PORT=9090
      - DRIVER=com.mysql.jdbc.Driver
      - DB_URL=
      - DB_USER=
      - DB_PASS=
    image: LearningWebsite:latest
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "9090:9090"
    restart: always